grails-app/controllers/edu/harvard/childrens/idm/HomeController.groovy
package edu.harvard.childrens.idm

class HomeController {

    def index() {
        redirect(URI: "/index" )
    }
}

grails-app/views/layouts/header_breadcrumb.gsp
<%--
  Created by IntelliJ IDEA.
  User: Kegler
  Date: 2/5/2015
  Time: 4:15 PM
--%>

<div class="breadcrumb-header">
    <h3>
        <ul class="breadcrumb">
            <li><g:link controller="home"><i class="icon-home"></i></g:link> <span class="divider">/</span></li>
            <g:if test="${controllerName in ['patient', 'enrollment']}">
                <g:if test="${params.action == 'list'}">
                    <li><g:link controller="patient" action="list">Subjects</g:link></li>
                </g:if>
                <g:else>
                    <li><g:link controller="patient" action="list">Subjects</g:link> <span class="divider">/</span></li>
                </g:else>

            </g:if>
            <g:elseif test="${controllerName == 'site'}">
                <li><g:link controller="site" action="list">Sites</g:link> <span class="divider">/</span></li>
            </g:elseif>
            <g:elseif test="${controllerName == 'study'}">
                <li><g:link controller="study" action="list">Studies</g:link> <span class="divider">/</span></li>
            </g:elseif>
            <g:elseif test="${controllerName == 'survey'}">
                <li><g:link controller="survey" action="list">Surveys</g:link> <span class="divider">/</span></li>
            </g:elseif>

            <g:layoutBody/>
        </ul>
    </h3>
</div>

S

grails-app/views/layouts/header_breadcrumb_item.gsp
<li class="${pageProperty(name:'activeItem') == 'true' ? 'active' : ''}">
    <g:layoutBody/>
    <g:if test="${pageProperty(name:'activeItem') == 'false' }">
        <span class="divider">/</span>
    </g:if>
</li>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Identity and Demographics Manager"/></title>
        <r:layoutResources/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
    
		<div id="chipLogo" role="banner">
            <a href="http://chip.org" target="_blank"><asset:image src="chiplogo_0.jpg" alt="Children's Hospital Health Informatics Program"/></a>
            <a href="http://www.childrenshospital.org/" target="_blank"><asset:image src="chb.png" alt="Boston Children's Hospital"/></a>
        </div>
    <g:render template="/includes/navbar"/>
		<g:layoutBody/>
        <r:layoutResources/>
    %{----}%
		%{--<div class="footer" role="contentinfo"></div>--}%
		%{--<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>--}%
    %{----}%
	</body>
</html>